- name: Terraform Init
  run: terraform init
  working-directory: environments/qa

- name: Terraform Plan
  run: terraform plan
  working-directory: environments/qa

- name: Terraform Apply
  run: terraform apply -auto-approve
  working-directory: environments/qa
