- name: Terraform Init
  working-directory: environments/qa
  run: terraform init

- name: Terraform Plan
  working-directory: environments/qa
  run: terraform plan

- name: Terraform Apply
  working-directory: environments/qa
  run: terraform apply -auto-approve
